#------------------------------------------------------------------
#     █████████  █████               ████   █████
#    ███░░░░░███░░███               ░░███  ░░███
#   ███     ░░░  ░███████    ██████  ░███  ███████    █████
#  ░███          ░███░░███  ███░░███ ░███ ░░░███░    ███░░
#  ░███    █████ ░███ ░███ ░███ ░███ ░███   ░███    ░░█████
#  ░░███  ░░███  ░███ ░███ ░███ ░███ ░███   ░███ ███ ░░░░███
#   ░░█████████  ████ █████░░██████  █████  ░░█████  ██████
#    ░░░░░░░░░  ░░░░ ░░░░░  ░░░░░░  ░░░░░    ░░░░░  ░░░░░░
#------------------------------------------------------------------
# TODO: add light mode
format = "[╭](bold fg:8)$username$directory$git_branch$git_status$cmd_duration $fill $line_break$character"
#------------------------------------------------------------------
add_newline = false
command_timeout = 5000
#------------------------------------------------------------------
[username]
show_always = true
format = " $user"
#------------------------------------------------------------------
[directory]
format = "[ $path](fg:1)"
truncation_length = 4
truncation_symbol = "+"
#------------------------------------------------------------------
[git_branch]
format = "[ $branch](fg:3)"
#------------------------------------------------------------------
[git_status]
format = "[ $modified](fg:5)"
#------------------------------------------------------------------
[cmd_duration]
min_time = 1000
show_milliseconds = false
disabled = false
format = "[ $duration](fg:2)"
#------------------------------------------------------------------
[fill]
symbol = "─"
style = "fg:#242424 bg:none"
#------------------------------------------------------------------
[character]
disabled = false
format = "[╰](fg:8) "
