watch_stylesheet: true
watch_config: true
debug: false
hide_taskbar: false

bars:
  primary-bar:
    enabled: true
    screens: ["H24T09P"]
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    blur_effect:
      enabled: true
      acrylic: true
      dark_mode: true
      round_corners: false
      border_color: none
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 32
    padding:
      top: 0
      left: 0
      bottom: 0
      right: 0
    widgets:
      left: ["active_window"]
      center: ["apps"]
      right: ["taskbar","weather","memory","volume","clock"]
  secondly-bar:
    enabled: true
    screens: ["DISPLAY2"]
    class_name: "yasb-bar"
    alignment:
      position: "top"
      center: false
    blur_effect:
      enabled: true
      acrylic: true
      dark_mode: true
      round_corners: true
      border_color: System
    window_flags:
      always_on_top: false
      windows_app_bar: true
    dimensions:
      width: "100%"
      height: 32
    padding:
      top: 3
      left: 2
      bottom: 3
      right: 2
    widgets:
      left: ["win_button","memory","traffic"]
      center: ["lang"]
      right: ["volume","clock"]
widgets:
  active_window:
    type: "yasb.active_window.ActiveWindowWidget"
    options:
      label: "{win[title]}"
      label_alt: "[class_name='{win[class_name]}' exe='{win[process][name]}' hwnd={win[hwnd]}]"
      label_no_window: ""
      label_icon: true
      label_icon_size: 14
      max_length: 60
      max_length_ellipsis: "..."
      monitor_exclusive: false
  clock:
    type: "yasb.clock.ClockWidget"
    options:
      label: "{%a, %d %b %H:%M}"
      label_alt: "{%A, %d %B %Y %H:%M:%S}"
      timezones: []
  weather:
    type: "yasb.weather.WeatherWidget"
    options:
      label: "<span>{icon}</span> {temp}"
      label_alt: "{location}: Min {min_temp}, Max {max_temp}, Humidity {humidity}"
      api_key: "3bf4cf9a7c3f40d6b31174128242807"
      show_alerts: true
      update_interval: 600
      hide_decimal: true
      units: "metric"
      location: ""
      callbacks:
        on_left: "toggle_card"
        on_right: "toggle_label"
      icons:
        sunnyDay: "\udb81\udd99"
        clearNight: "\udb81\udd99"
        cloudyDay: "\udb81\udd99"
        cloudyNight: "\udb81\udd99"
        rainyDay: "\udb81\udd99"
        rainyNight: "\udb81\udd99"
        snowyIcyDay: "\udb81\udd99"
        snowyIcyNight: "\udb81\udd99"
        blizzard: "\udb81\udd99"
        default: "\udb81\udd99"
      weather_card: 
        blur: True
        round_corners: True
        round_corners_type: "normal"
        border_color: "System"
        alignment: "right"
        direction: "down"
        distance: 6
        icon_size: 64
  volume:
    type: "yasb.volume.VolumeWidget"
    options:
      label: "<span>{icon}</span> {level}"
      label_alt: "{volume}"
      volume_icons:
        - "\ueee8"
        - "\uf026"
        - "\uf027"
        - "\uf027"
        - "\uf028"
      callbacks:
        on_right: "exec cmd.exe /c start ms-settings:sound"
  apps:
    type: "yasb.applications.ApplicationsWidget"
    options:
      container_padding:
        top: 0
        left: 8
        bottom: 0
        right: 8
      label: "{data}"
      app_list:
        - { icon: "\uf4b5", launch: "wt" }
        - { icon: "\uf07c", launch: "explorer" }
        - { icon: "\ue696", launch: "D:\\Sublime Text\\sublime_text.exe" }
        - { icon: "\uf1ff",launch: "C:\\Users\\GhostMxv\\AppData\\Local\\Discord\\Update.exe --processStart Discord.exe" }
        - { icon: "\ue217",launch: "D:\\AyuGram\\AyuGram.exe" }
        - { icon: "\uf1d7",launch: "D:\\WeChat\\Weixin\\Weixin.exe" }
        - { icon: "\uf268",launch: "C:\\Users\\GhostMxv\\AppData\\Local\\Thorium\\Application\\thorium.exe" }
        - { icon: "\uf1bc",launch: "C:\\Users\\GhostMxv\\AppData\\Roaming\\Spotify\\Spotify.exe" }
  github:
    type: "yasb.github.GithubWidget"
    options:
      label: "<span>\ueba1</span>"
      label_alt: "Notifications {data}"
      token: env
      max_notification: 30
      only_unread: false
      max_field_size: 54
      menu_width: 400
      menu_height: 400
      menu_offset: 240
      update_interval: 60
  taskbar:
    type: "yasb.taskbar.TaskbarWidget"
    options:
      animation: true
      icon_size: 16
      ignore_apps:
        processes: []
        titles: []
        classes: []
      container_padding:
        top: 0
        left: 0
        bottom: 0
        right: 0
  memory:
    type: "yasb.memory.MemoryWidget"
    options:
      label: "<span>\uefc5</span> {virtual_mem_percent}%"
      label_alt: "<span>\uefc5</span> {virtual_mem_free}"
      update_interval: 10000
      callbacks:
        on_right: "exec cmd /c Taskmgr"
  traffic:
    type: "yasb.traffic.TrafficWidget"
    options:
      label: "<span>\udb86\uddb3</span>{download_speed}<span class=\"tr_sep\">\ue621</span><span>\udb86\uddb2</span>{upload_speed}"
      label_alt: "Download {download_speed} \ue621 Upload {upload_speed}"
      update_interval: 1000 # Update interval should be a multiple of 1000
      callbacks:
        on_left: "toggle_label"
        on_right: "exec cmd /c Taskmgr"
  win_button:
      type: "yasb.custom.CustomWidget"
      options:
        label: "\ue62a"
        label_alt: "\ue62a"
        class_name: "system-widget"
        callbacks:
          on_left: "exec start_menu"
  lang:
      type: "yasb.custom.CustomWidget"
      options:
        label: "<span>\uf1ab</span>{data}"
        label_alt: "{data}"
        class_name: "lang-widget"
        exec_options:
          run_cmd: "powershell Add-Type -AssemblyName System.Windows.Forms;([System.Windows.Forms.InputLanguage]::CurrentInputLanguage).Culture.Name"
          # run every 10 sec
          run_interval: 500
          return_format: "string"