format = """
$python\
$username\
$directory\
$git_branch\
$git_status\
$c\
$golang\
$java\
$nodejs\
$rust\
$docker_context\
$cmd_duration\
$fill\
$time\
$line_break$character"""

command_timeout = 5000
# Disable the blank line at the start of the prompt
# add_newline = false

[cmd_duration]
min_time = 1000
show_milliseconds = false
disabled = false
format="[ 󰞌 $duration ]($style)"
style="bold bg:62"

[character]
disabled = false
success_symbol = '[](bold fg:green)'
error_symbol = '[](bold fg:red)'
vimcmd_symbol = '[](bold fg:green)'
vimcmd_replace_one_symbol = '[](bold fg:purple)'
vimcmd_replace_symbol = '[](bold fg:purple)'
vimcmd_visual_symbol = '[](bold fg:yellow)'

[username]
show_always = true
style_user = "bg:235"
style_root = "bg:53"
format = '[ $user ]($style)'

[directory]
style = "bg:237"
format = "[ $path ]($style)"
truncation_length = 0
truncation_symbol = "…/"

[directory.substitutions]
"Documents" = "󰈙 "
"Downloads" = " "
"Music" = " "
"Pictures" = " "

[c]
symbol = " "
style = "bg:61"
format = '[ $symbol ($version) ]($style)'

[docker_context]
symbol = " "
style = "bg:10"
format = '[ $symbol $context ]($style)$path'

[git_branch]
symbol = ""
style = "bg:60"
format = '[ $symbol $branch ]($style)'

[git_status]
style = "bg:60"
format = '[$all_status$ahead_behind ]($style)'

[golang]
symbol = " "
style = "bg:61"
format = '[ $symbol ($version) ]($style)'

[java]
symbol = " "
style = "bg:61"
format = '[ $symbol ($version) ]($style)'

[nodejs]
symbol = ""
style = "bg:61"
format = '[ $symbol ($version) ]($style)'

[python]
style = "bg:60"
format = '[(\($virtualenv\) )]($style)'

[rust]
symbol = ""
style = "bg:61"
format = '[ $symbol ($version) ]($style)'

[time]
disabled = false
time_format = "%R" # Hour:Minute Format
style = "bg:62"
format = '[ $time ]($style)'

[fill]
symbol = ' '
style = 'bg:none'
